### ISSUE TITLE
Pretty new to this.. but it does look like a resource needed to 'yarn install' is no longer accessible at Walmart Labs.

### ISSUE THREAD

**Issue by jyaunches** [electrode-io/MovieListMiniApp#7]
![screen shot 2017-10-20 at 6 45 53 pm](https://user-images.githubusercontent.com/372490/31844598-b00e0260-b5c7-11e7-8c60-21111a0ef40b.png)

**Comment by belemaire** [comment]
@jyaunches Thanks much ! 
Fixed by https://github.com/electrode-io/MovieListMiniApp/pull/8
